from enum import Enum

GAME_SCALE_FACTOR = 2
TILE_SIZE = 16 * GAME_SCALE_FACTOR
TOP_OFFSET = 60
END_MENU_WIDTH = 200

HISTORY_ITEM_HEIGHT = 25
SCROLL_FACTOR = 20


MIN_WIDTH = 8
MIN_HEIGHT = 8

MAX_WIDTH = 30
MAX_HEIGHT = 30

MIN_MINES = 8
MAX_MINES_PERCENTAGE = 0.4

class MouseButton(Enum):
    MOUSE_LEFT = 1
    MOUSE_RIGHT = 2
    MOUSE_SCROLL_DOWN = 3
    MOUSE_SCROLL_UP = 4

MINE = "mine"

class TileState(Enum):
    UNKNOWN = 1
    FLAGGED = 2
    VISIBLE = 3
